Repository mautic/mautic-documentation, pull requests merged in 2020-12, with the labels that each got.

#141 Improve segment documentation and add documentation for #8238
  pages/09.contacts/03.manage-segments/docs.en.md
  pages/09.contacts/03.manage-segments/public-segment-name.png
Labels: Pending PR Merging

#118 Added documentation for PR #9026
  pages/09.contacts/01.manage-contacts/01.contact-overview/docs.en.md
Labels: Pending PR Merging

#132 add doc for 6126 - relative date support in campaigns
  pages/05.Campaigns/03.Campaign Events/docs.en.md
Labels: enhancement

#148 Update different callback URL for the Amazon SES API
  pages/07.Channels/02.Emails/03.Bounce management/docs.en.md
Labels: Mautic 3
