Repository mautic/mautic-documentation, pull requests merged in 2020-06, with the labels that each got.

#70 improve docs and images in maxmind license docs
  .DS_Store
  pages/.DS_Store
  pages/02.Setup/.DS_Store
  pages/02.Setup/05.maxmind-license/.DS_Store
  pages/02.Setup/05.maxmind-license/docs.en.md
  pages/02.Setup/05.maxmind-license/mautic-maxmind-account.png
  pages/02.Setup/05.maxmind-license/mautic-maxmind-license-key.png
  pages/02.Setup/05.maxmind-license/maxmind-confirm-key.png
  pages/02.Setup/05.maxmind-license/maxmind-generate-key-2.png
  pages/02.Setup/05.maxmind-license/maxmind-generate-key.png
  pages/02.Setup/05.maxmind-license/maxmind-license-key-2.png
  pages/02.Setup/05.maxmind-license/maxmind-license-key.png
Labels: changes requested

#61 Update broken links
  pages/02.Setup/01.Getting Started/docs.en.md
  pages/02.Setup/03.Cron Jobs/docs.en.md
  pages/02.Setup/04.Variables/docs.en.md
  pages/03.Troubleshooting/docs.en.md
  pages/07.Channels/01.Marketing Messages/02.Notifications/docs.en.md
  pages/07.Channels/02.Emails/03.Bounce management/docs.en.md
  pages/10.Components/04.Pages/01.Managing Pages/docs.en.md
  pages/10.Components/04.Pages/02.Device granularity/docs.en.md
  pages/12.Plugins/04.Clearbit/docs.en.md
  pages/12.Plugins/05.Connectwise/docs.en.md
  pages/12.Plugins/06.FullContact/docs.en.md
  pages/12.Plugins/07.Gmail/docs.en.md
  pages/12.Plugins/08.Hubspot/docs.en.md
  pages/12.Plugins/09.iContact/docs.en.md
  pages/12.Plugins/10.Mailchimp/docs.en.md
  pages/12.Plugins/11.Microsoft Dynamics CRM/docs.en.md
  pages/12.Plugins/12.Microsoft Outlook/docs.en.md
  pages/12.Plugins/14.Salesforce/docs.en.md
  pages/12.Plugins/15.Social login/docs.en.md
  pages/12.Plugins/16.SugarCRM/docs.en.md
  pages/12.Plugins/18.Twitter/docs.en.md
  pages/12.Plugins/19.VTiger/docs.en.md
  pages/12.Plugins/20.Zapier/docs.en.md
  pages/12.Plugins/docs.en.md
  pages/13.Points/01.Troubleshooting/docs.en.md
  pages/14.Queue/docs.en.md
  pages/18.Themes/01.Manage themes/docs.en.md
  pages/18.Themes/03.Theme structure/docs.en.md
  pages/18.Themes/docs.en.md
  pages/19.Translations/docs.en.md
Labels: WIP, changes requested

#67 Updated Reports page to add info about scheduled sending of reports
  pages/15.Reports/config.png
  pages/15.Reports/data-source.png
  pages/15.Reports/docs.en.md
  pages/15.Reports/graphs.png
  pages/15.Reports/schedule.png
Labels: changes requested

#64 Mautic 3.0 documentation changes
  pages/02.Setup/01.Getting Started/docs.en.md
  pages/02.Setup/02.updating-at-command-line/docs.en.md
  pages/03.Troubleshooting/01.Command line tools/docs.en.md
  pages/03.Troubleshooting/02.Update Failed/docs.en.md
  pages/05.Campaigns/01.Managing Campaigns/docs.en.md
  pages/07.Channels/02.Emails/02.Contact replies/docs.en.md
  pages/07.Channels/02.Emails/03.Bounce management/docs.en.md
  pages/07.Channels/02.Emails/docs.en.md
  pages/07.Channels/04.Social Monitoring/docs.en.md
  pages/09.contacts/02.import-contacts/docs.en.md
  pages/09.contacts/03.manage-segments/docs.en.md
  pages/09.contacts/07.message-queue/docs.en.md
  pages/12.Plugins/03.Citrix/docs.en.md
  pages/12.Plugins/05.Connectwise/docs.en.md
  pages/12.Plugins/11.Microsoft Dynamics CRM/docs.en.md
  pages/12.Plugins/14.Salesforce/docs.en.md
  pages/12.Plugins/16.SugarCRM/docs.en.md
  pages/14.Queue/docs.en.md
  pages/22.What's New/docs.en.md
  pages/22.What's New/file-manager.png
Labels: Mautic 3, Pending PR Merging

#49 Update to reflect changes in CLI with Mautic 3.x
  pages/03.Troubleshooting/01.Command line tools/docs.en.md
Labels: Mautic 3
