Repository mautic/mautic-documentation, pull requests merged in 2020-08, with the labels that each got.

#105 update company page about company overview
  pages/09.contacts/08.Companies/docs.en.md
Labels: Pending PR Merging

#101 Send JSON Webhooks in campaigns when content-type of application/json is included in the header
  pages/05.Campaigns/03.Campaign Events/docs.en.md
  pages/05.Campaigns/03.Campaign Events/send-json-webhooks.png
Labels: Mautic 3, Pending PR Merging

#98 add a short line about #8699
  pages/10.Components/03.Forms/01.Managing Forms/docs.en.md
Labels: Mautic 3, Pending PR Merging

#117 Made changes to grammar and wording
  pages/10.Components/03.Forms/02.Progressive Profiling/docs.en.md
Labels: pending feedback
