Repository mautic/mautic-documentation, pull requests merged in 2021-08, with the labels that each got.

#207 9978 segment delete warning
  pages/10.contacts/03.manage-segments/delete-segment-alert.png
  pages/10.contacts/03.manage-segments/docs.en.md
Labels: Pending PR Merging, Mautic 4

#189 Alter Queue Configuration docs for #9391
  pages/16.Queue/docs.en.md
Labels: Parent PR merged

#134 added documentation for #9364
  pages/12.Plugins/22.TagManager/.docs.en_images/create_tag.png
  pages/12.Plugins/22.TagManager/.docs.en_images/menu_icon.png
  pages/12.Plugins/22.TagManager/.docs.en_images/overview.png
  pages/12.Plugins/22.TagManager/docs.en.md
Labels: enhancement, Pending PR Merging
